// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNbK38edpav4VvQXxGrHB17-UxST_ozXg',
    appId: '1:924211090980:web:a4cc28e74af9bfca692ab1',
    messagingSenderId: '924211090980',
    projectId: 'dining-dash-90a09',
    authDomain: 'dining-dash-90a09.firebaseapp.com',
    storageBucket: 'dining-dash-90a09.appspot.com',
    measurementId: 'G-6NGEZ2XMC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2qgq0vfEP4jAubH4iIuHc_Gv14AkFwFY',
    appId: '1:924211090980:android:9e7858ecafc8edff692ab1',
    messagingSenderId: '924211090980',
    projectId: 'dining-dash-90a09',
    storageBucket: 'dining-dash-90a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVYkY7bzh6Vt_62-5voryiFZAMjpoQFRU',
    appId: '1:924211090980:ios:c6198d5f66f3b231692ab1',
    messagingSenderId: '924211090980',
    projectId: 'dining-dash-90a09',
    storageBucket: 'dining-dash-90a09.appspot.com',
    iosBundleId: 'com.example.diningDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVYkY7bzh6Vt_62-5voryiFZAMjpoQFRU',
    appId: '1:924211090980:ios:84bef579938d21fb692ab1',
    messagingSenderId: '924211090980',
    projectId: 'dining-dash-90a09',
    storageBucket: 'dining-dash-90a09.appspot.com',
    iosBundleId: 'com.example.diningDash.RunnerTests',
  );
}
